### ISSUE TITLE
locking functionality

### ISSUE THREAD

**Issue by trbck** [spenczar/quivr#57]
hi there, is there a locking functionality to ensure e.g. write once or queued/ structured writing to the table from multiple processes?

**Comment by spenczar** [comment]
Hi. Tables are immutable. There is no way for multiple processes to write to the same memory region. If they manipulated a table, like to change the values in a column with `set_column`, then they would be producing a copy of the Table instance. All the methods on `Table` that appear to modify a Table return a new Table instance for that reason.

Only the modified column's array data would be copied - the other arrays would be unchanged.
